name: Build and Push images to dockerhub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: .
            dockerfile: ./database/migrations/Dockerfile 
            image: jonguijarro/clomonitor-dbmigrator
          - context: .
            dockerfile: ./clomonitor-apiserver/Dockerfile 
            image: jonguijarro/clomonitor-apiserver
          - context: .
            dockerfile: ./clomonitor-archiver/Dockerfile 
            image: jonguijarro/clomonitor-archiver
          - context: .
            dockerfile: ./clomonitor-linter/Dockerfile 
            image: jonguijarro/clomonitor-linter
          - context: .
            dockerfile: ./clomonitor-notifier/Dockerfile 
            image: jonguijarro/clomonitor-notifier
          - context: .
            dockerfile: ./clomonitor-registrar/Dockerfile 
            image: jonguijarro/clomonitor-registrar
          - context: .
            dockerfile: ./clomonitor-tracker/Dockerfile 
            image: jonguijarro/clomonitor-tracker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}:${{ github.sha }}
